test

diff --git a/NGSmodule b/NGSmodule
--- a/NGSmodule
+++ b/NGSmodule
@@ -107,6 +107,18 @@ GATK-somatic-CNV() {
   source $shell_folder/Analysis/GATK/GATK-somatic-CNV.sh
 }
 
+Strelka2-germline-short-variant(){
+  source $1
+  source $shell_folder/LoadConfig.sh
+  source $shell_folder/Analysis/Strelka2/Strelka2-germline-short-variant.sh
+}
+
+Strelka2-somatic-short-variant(){
+  source $1
+  source $shell_folder/LoadConfig.sh
+  source $shell_folder/Analysis/Strelka2/Strelka2-somatic-short-variant.sh
+}
+
 CreateSCPConfigFile() {
   source $shell_folder/SingleCellPipe/SCP-PreparationSteps/CreateSCPConfigFile.sh $1
 }
@@ -182,6 +194,10 @@ help() {
        GATK-somatic-short-variant
        GATK-germline-CNV
        GATK-somatic-CNV
+    
+    # Strelka2:
+      Strelka2-germline-short-variant
+      Strelka2-somatic-short-variant
     
     # SingleCellPipe
        CreateSCPConfigFile
@@ -342,7 +358,7 @@ while true; do
     elif [[ $1 == "GATK-germline-short-variant" ]]; then
       { echo "$parameters" | grep -E '\-\-ConfigFile|\-c'; } &>/dev/null
       [ $? -ne 0 ] && {
-        echo -e "ERROR!\nOption -c|--ConfigFile needed in GATK-somatic-short-variant MODE!\nTry '$0 --help' for more information.\n"
+        echo -e "ERROR!\nOption -c|--ConfigFile needed in GATK-germline-short-variant MODE!\nTry '$0 --help' for more information.\n"
         exit 1
       }
       CheckConfigFile $ConfigFile
@@ -360,7 +376,7 @@ while true; do
     elif [[ $1 == "GATK-germline-CNV" ]]; then
       { echo "$parameters" | grep -E '\-\-ConfigFile|\-c'; } &>/dev/null
       [ $? -ne 0 ] && {
-        echo -e "ERROR!\nOption -c|--ConfigFile needed in GATK-somatic-short-variant MODE!\nTry '$0 --help' for more information.\n"
+        echo -e "ERROR!\nOption -c|--ConfigFile needed in GATK-germline-CNV MODE!\nTry '$0 --help' for more information.\n"
         exit 1
       }
       CheckConfigFile $ConfigFile
@@ -369,12 +385,31 @@ while true; do
     elif [[ $1 == "GATK-somatic-CNV" ]]; then
       { echo "$parameters" | grep -E '\-\-ConfigFile|\-c'; } &>/dev/null
       [ $? -ne 0 ] && {
-        echo -e "ERROR!\nOption -c|--ConfigFile needed in GATK-somatic-short-variant MODE!\nTry '$0 --help' for more information.\n"
+        echo -e "ERROR!\nOption -c|--ConfigFile needed in GATK-somatic-CNV MODE!\nTry '$0 --help' for more information.\n"
         exit 1
       }
       CheckConfigFile $ConfigFile
       GATK-somatic-CNV $ConfigFile
       exit 0
+    elif [[ $1 == "Strelka2-germline-short-variant" ]]; then
+      { echo "$parameters" | grep -E '\-\-ConfigFile|\-c'; } &>/dev/null
+      [ $? -ne 0 ] && {
+        echo -e "ERROR!\nOption -c|--ConfigFile needed in Strelka2-germline-short-variant MODE!\nTry '$0 --help' for more information.\n"
+        exit 1
+      }
+      CheckConfigFile $ConfigFile
+      Strelka2-germline-short-variant $ConfigFile
+      exit 0
+    elif [[ $1 == "Strelka2-somatic-short-variant" ]]; then
+      { echo "$parameters" | grep -E '\-\-ConfigFile|\-c'; } &>/dev/null
+      [ $? -ne 0 ] && {
+        echo -e "ERROR!\nOption -c|--ConfigFile needed in Strelka2-somatic-short-variant MODE!\nTry '$0 --help' for more information.\n"
+        exit 1
+      }
+      CheckConfigFile $ConfigFile
+      Strelka2-somatic-short-variant $ConfigFile
+      exit 0
+
 
     ### SingleCellPipe
     elif [[ $1 == "CreateSCPConfigFile" ]]; then
